name: Card Event Processing

# Trigger on repository_dispatch event with card_interaction_event type
on:
  repository_dispatch:
    types: [card_interaction_event]

jobs:
  process-events:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Process card events
        id: process-events
        run: |
          echo "Processing card interaction events"
          echo "Event received at: $(date)"
          echo "Session ID: ${{ github.event.client_payload.sessionId }}"
          echo "Number of interactions: ${{ github.event.client_payload.interactions.length }}"
          
          # Extract relevant data from the payload
          echo "Device capabilities:"
          echo "- Touch: ${{ github.event.client_payload.deviceCapabilities.touch }}"
          echo "- Screen size: ${{ github.event.client_payload.deviceCapabilities.screenWidth }}x${{ github.event.client_payload.deviceCapabilities.screenHeight }}"
          echo "- Reduced motion: ${{ github.event.client_payload.deviceCapabilities.reducedMotion }}"
          
          # Store processed data (could save to a database or file)
          # This would normally call a script to process the data:
          # node scripts/process-card-events.js "${{ toJSON(github.event.client_payload) }}"
          
          # For now, we'll just create summary metrics
          echo "TOTAL_INTERACTIONS=${{ github.event.client_payload.interactions.length }}" >> $GITHUB_ENV
          echo "SESSION_DURATION=${{ github.event.client_payload.sessionDuration || 0 }}" >> $GITHUB_ENV
      
      - name: Send to optimization pipeline if final
        if: ${{ github.event.client_payload.isFinal == true }}
        run: |
          echo "Final session data received. Triggering optimization."
          echo "Session duration: ${{ env.SESSION_DURATION }}ms"
          echo "Total interactions: ${{ env.TOTAL_INTERACTIONS }}"
          
          # Here we would trigger the card optimization workflow:
          # gh workflow run card-optimization.yml -f sessionId=${{ github.event.client_payload.sessionId }}