name: GitHub Pages Deploy

on:
  push:
    branches: [ main, gh-pages-deploy ]
  workflow_dispatch: # Enable manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci

      - name: Run accessibility tests
        run: |
          # Add NO_DEPRECATION flag to suppress deprecation warnings
          NODE_NO_DEPRECATION=1 npm run test:a11y
        continue-on-error: true  # Don't fail the build if tests fail

      - name: Generate accessibility report
        run: |
          # Add NO_DEPRECATION flag to suppress deprecation warnings
          NODE_NO_DEPRECATION=1 npm run test:report
          
          # Verify the report was generated
          if [ -f "test-report/index.html" ]; then
            echo "Test report generated successfully!"
          else
            echo "Warning: No test report was generated. Creating directory to ensure later steps work."
            mkdir -p test-report
          fi
        continue-on-error: true  # Ensure we can still deploy even if report generation fails

      - name: Build project
        run: |
          # Add NO_DEPRECATION flag to suppress deprecation warnings
          NODE_NO_DEPRECATION=1 npm run build:prod

      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          # Copy HTML files from root
          cp index.html multi-card.html demo-card.html react-card.html _site/
          
          # Copy directories with source files
          mkdir -p _site/src
          cp -r src/components src/images src/js src/styles _site/src/
          
          # Copy React components
          cp -r react-components _site/react-components
          
          # Ensure dist directory exists and copy all files
          mkdir -p _site/dist/css _site/dist/js
          cp -r dist/css/* _site/dist/css/ || true
          cp -r dist/js/* _site/dist/js/ || true
          
          # Copy documentation and reports
          mkdir -p _site/test-report
          
          # Copy test reports, create placeholder if none exist
          if [ -f "test-report/index.html" ]; then
            cp -r test-report/* _site/test-report/ || true
          else
            echo "<html><body><h1>Test Report</h1><p>Tests were run but no report was generated during this build.</p></body></html>" > _site/test-report/index.html
          fi
          
          # Copy documentation files
          cp README.md _config.yml _site/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Ensure test report is generated properly before uploading
      - name: Prepare test report for artifact
        run: |
          # Create a directory for the report if it doesn't exist
          mkdir -p test-report-artifact

          # Copy the test report if it exists
          if [ -f "test-report/index.html" ]; then
            cp test-report/index.html test-report-artifact/
            echo "Found and copied test report"
          else
            # Create a simple report if the real one doesn't exist
            echo "<html><body><h1>Test Report</h1><p>Tests were run but no report was generated.</p></body></html>" > test-report-artifact/index.html
            echo "Created placeholder test report"
          fi

      # Upload test report as a separate artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-report-artifact
          if-no-files-found: warn

      # Upload pages artifact
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4