name: GitHub Pages Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Enable manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test: # Renamed for clarity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

      - name: Run accessibility tests
        run: npm run test:a11y

      - name: Generate accessibility report
        run: npm run test:report

      - name: Build project
        run: npm run build:prod

      - name: Prepare deployment directory
        run: |
          mkdir -p _site
          # Copy main HTML files
          cp -r index.html multi-card.html _site/
          
          # Copy component directories
          cp -r src/components _site/components
          cp -r src/react-components _site/react-components
          
          # Copy assets
          cp -r dist/css dist/js _site/
          cp -r src/images _site/
          
          # Copy documentation and reports
          cp -r test-report _site/
          cp -r src/docs _site/docs
          cp README.md _config.yml _site/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test # Updated to match new job name
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4